stati:
  first:
    default: "&7█"
    dnd: "&#ff0000█"
    open: "&#00ff00█"

  second:
    default: "&7█"
    recording: "&#ff0000█"
    streaming: "&#ffff00█"
features:
  arena: true
  autorefill: true
  status: true
  shulker: true
  keepimportant: true
  dumpinventory: true
  backpack: true
  vine: true
  afksave: true
  creeper: true