name: QualityofLife
version: '${project.version}'
main: de.snowwars.qualityoflife.Qualityoflife
api-version: 1.19
commands:
  status:
    description: Changes the Player Status
    permission: status
  arena:
    description: Adds an arena
    permission: arena
  backpack:
    description: Opens the Backpack
    permission: backpack
  alert:
    description: Customize your command settings
    permission: alert
permissions:
    status:
        description: Changes the Player Status
        default: true
    arena:
        description: Adds an arena
        default: op
    backpack:
        description: Opens the Backpack
        default: true
    alert:
        description: Alerts the Player
        default: true