
name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: 
      - closed

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
         files: /home/runner/work/qualityoflife/qualityoflife/target/qualityoflife-1.0-SNAPSHOT.jar
         tag-name: "v0.0.1"
