
name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    type: 

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
         files: /home/runner/work/qualityoflife/qualityoflife/target/qualityoflife-1.0-SNAPSHOT.jar
